### ISSUE TITLE
Hexion music too fast

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1117]
Hello
In the videogame hexion from konami the music is too fast in mame also the music is too fast please fix it thanks

**Comment by barbudreadmon** [comment]
I can't find any pcb video to confirm this.

**Comment by otk-010199** [comment]
https://youtu.be/DyXs4oTaExU for PCB footage, https://www.youtube.com/playlist?list=PLfUvsxulQQd-eH0pibwh2P_L2dNGhP90B for the soundtrack recorded from PCB.  Music is currently ~20% too slow in fbneo (60 ticks/second as opposed to proper 72 ticks/second) due to an unemulated fixed-scanline-delay timer firing from the CRTC, MAME fixed this some versions ago and has the correct tempo.

**Comment by barbudreadmon** [comment]
Ok, it seems to refer to https://github.com/mamedev/mame/commit/b88f3b7dd289956634f8717208accc36a816be68 and https://github.com/mamedev/mame/commit/c6c70bbf0e827088ade73fc3ed0d4a29d16d821a , replacing https://github.com/finalburnneo/FBNeo/blob/5a92c86f46cb5e7f3bf3268103a99b7cd5baf4db/src/burn/drv/konami/d_hexion.cpp#L539-L540

I'm kinda busy this week-end but i'll try backporting it soon if no one does it before me.

**Comment by MistyDreams** [comment]
https://github.com/mamedev/mame/blob/b88f3b7dd289956634f8717208accc36a816be68/src/devices/machine/k053252.cpp#L1

**Comment by dinkc64** [comment]
barbudreadmon, I fixed it last night, holding back upload because I'm trying to work out a small problem with the laser zaps before the music start on the 6295.

**Comment by dinkc64** [comment]
nobody has a video or sound footage of pcb for the sfx after the konami logo?  sadly the guy that played it for nearly 2 hours muted the game right before the Konami logo/title sound @ the end, so that was no help.  same with the game soundtrack, it doesn't play the special sfx after the Konami logo voice....

**Comment by dinkc64** [comment]
I got it pretty close to the soundtrack, it's not 100%, but, close as possible for now.

best regards,
- dink
