### ISSUE TITLE
Demons of Asteborg (MD) grapic glitch.

### ISSUE THREAD

**Issue by Hexagum** [finalburnneo/FBNeo#1132]
Game: md_asteborg (asteborg) Sega Megadrive.
Issue: I guess, game has some graphic feature or effect which is wrongly emulated.
Where it happens: 
During the boss fight in Mountain level.  If you use timestop when dragon using breath from background something goes wrong (savestate 02).
![md_asteborg-08-01-215933](https://user-images.githubusercontent.com/110428435/182253210-828891d1-4006-4d71-8da8-7dca2a829300.png)
During the bonus Nightmare level. In the beginning, after drop into the pit everything goes wrong (savestate 01).
![md_asteborg-08-01-211727](https://user-images.githubusercontent.com/110428435/182248679-7e9fc064-52ab-432a-b7a0-45146979bdc4.png)
Savestates:
[savestates.zip](https://github.com/finalburnneo/FBNeo/files/9237572/savestates.zip)

**Comment by dinkc64** [comment]
Hi, thanks for the bug report & savestates.  I've been working on the nightmare level bug first, since it seems the most serious, here's the conclusion:
it's a game bug in version 1.1 of the game.  Using your sram (in the savestate) I went to the nightmare level on other emulators and get the same exact effect.
Try using 1.0 (asteborg10 romset) nightmare world, which ends up in an even weirder error that matches the recordings on youtube.

p.s. I'll post back when I find out what's wrong with the mountain level boss

best regards,
- dink

**Comment by dinkc64** [comment]
Timestop when dragon is blowing fire, right as the screen flashes will cause that effect, and it's not wrong (not a bug), it will do the same thing in any other emu or machine.

best regards,
- dink

**Comment by Hexagum** [comment]
Thanks for such quick response!

**Comment by dinkc64** [comment]
you're welcome :)
