### ISSUE TITLE
Keybinding does not work on Arch Linux with fbneo-git

### ISSUE THREAD

**Issue by Agvantibo** [finalburnneo/FBNeo#1177]
I have installed FinalBurn Neo via Arch Linux AUR (https://aur.archlinux.org/packages/fbneo-git), and it seems to work alright, but for some reason, F5, which is listed in keys.md as the only way to remap controls would not register as pressed. The program outputs nothing to stdout about this, as if no keypress has ever happened. F5 registers just fine in the OS and other apps like Firefox, so it's definitely a FBNeo problem.
I've tried the manual config, but it uses coded hexadecimals for keys, so I haven't been able to figure it out.
Any translation list or tips on fixing F5 would be greatly appreciated

**Comment by dinkc64** [comment]
That version is quite old, recently @cjom has worked on improving the keyboard input code for the sdl2 version, you might want to try to build it from the current source.

best regards,
- dink

**Comment by cjom** [comment]
> (...) If you press tab it will bring a menu up (...)

Yes, this is the way :)

**Comment by cjom** [comment]
You mean in Arch Linux?
Because it seems OK for me in Ubuntu:

![menu](https://user-images.githubusercontent.com/55603581/192643168-a44ef59f-1475-4ce1-9288-074d7f6ee711.png)
![p1](https://user-images.githubusercontent.com/55603581/192643173-7ec078ed-f12a-434c-a1e1-a36e67f445fa.png)
![p2](https://user-images.githubusercontent.com/55603581/192643179-2c9de559-af89-4cef-adb1-c377df200cca.png)

**Comment by cjom** [comment]
For this screenshots I had deleted all files and tested jojo and sf2ce

**Comment by cjom** [comment]
That error seems to happen because of some "empty" line in fbneo.ini - and it shouldn't happen - but I think it is not related, unless there is some memory corruption very peculiar...

**Comment by dinkc64** [comment]
Bugs like that can end up doing very nasty things which are hard to track down.. if szLine[-1] actually was == 10, then it would basically be writing a 0 to an unknown place in memory.  yikes :)
I put in a little guard for that, hope you don't mind.  If you want to fix it a different way, feel free.

best regards,
- dink

**Comment by dinkc64** [comment]
any better after https://github.com/finalburnneo/FBNeo/commit/20d573e12998b9163fd865c87c97c4361abffd41 ?

**Comment by dinkc64** [comment]
I wasn't trying to fix any problems here other than potential crasher issues, sorry

**Comment by cjom** [comment]
@MistyDreams the fix for selected player in default menu looks like it will work, although I'm questioning myself why didn't I just subtracted the number of players. 
But I can't look into this until Friday...

**Comment by cjom** [comment]
Made the fixes pointed by @MistyDreams and tests was good but found other errors :(

Also, answering my own question, one could not just subtract number of players because there is also number of joysticks (and this number is not reliable because one can remove and plug again, etc).

About the "index 34 out of bounds for type 'playerInputInfo [34]'" error it is also fixed, it was not supposed to copy from this array at this point.
This and the next error makes me think I somehow made a stupid mistake using "old" code when I made the pull request.

I still need some more time to fix this: when saving default inputs, "old" inputs stops working but "new" inputs wont work until we exit game and restart.
