### ISSUE TITLE
poker ladies  ,controls missing

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1209]
in poker ladies i cant choose the cards, there is no keymaps to select cards (1-5), only button that workds is the deal.

**Comment by barbudreadmon** [comment]
This one is considered a mahjong game and we map mahjong controls to the keyboard. 
It uses 5 of them : A, B, C, D, E.

**Comment by kounabi22** [comment]
is there a way to edit something and put keys from gamepad?

**Comment by barbudreadmon** [comment]
Retroarch lacks the flexibility to remap anything anywhere.

In this case, in our code, i suppose we could use fire 4/5/6/7/8 instead of mah a/b/c/d/e since the game isn't a real mahjong game and doesn't have that many buttons. But don't expect that kind of workaround to be appliable for other mahjong games.

@dinkc64 should i make this change for libretro only or should i extend it to standalone ?

**Comment by kounabi22** [comment]
thanks
