### ISSUE TITLE
Dragon Breed freezes gfx on title screen

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1219]
dbreed remains freezed on title screen until credit is inserted. Something related to apply hiscore memory range 2. Their M71 clones dont stop the title animation.

**Comment by dinkc64** [comment]
Hi, can you try to delete dbreed.hi and see if it helps?  if then it happens again, please say.

best regards,
- dink

**Comment by dinkc64** [comment]
hmm, ignore that - after a few games it goes back to the same bad behavior.  will need investigating further, stay tuned :)

**Comment by barbudreadmon** [comment]
>Their M7**2** clones dont stop the title animation.

The M72 version was renamed from `dbreed` back in 2006, its entry in hiscore.dat probably never got updated.

**Comment by dinkc64** [comment]
There's a huge problem with this hiscore entry - the last byte in it is the game's animation timer.  our hiscore engine writes the hiscore data + this byte, then checks on subsequent frame if data stayed in ram, if not, it keeps retrying.  Since the animation timer changes every frame, and fbneo keeps re-applying it to memory because it thinks the hiscore data isn't "sticking", the animation is stuck.
Not sure how to handle this at this time...
best regards,
- dink

**Comment by barbudreadmon** [comment]
but the same happens in mame, right ? i believe nobody checked/updated that entry in 2006 when the m81 variant replaced the original m72 variant as parent ? i've seen similar issues with other hiscore.dat entries

**Comment by dinkc64** [comment]
works fine in mame, because mame doesn't verify the data on the next frame like we do (we ensuring that hiscore data doesn't get clobbered)
I think I'll add an in-code kludge for this one...

**Comment by dinkc64** [comment]
I've added a fix for this to hiscore.cpp, thanks for your bug report and sorry it took long to find a solution!

best regards,
- dink

**Comment by coyonut** [comment]
Thanks to you for your efforts :)
