### ISSUE TITLE
B-Wings and Zaviga (same driver) graphical issue.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#128]
B-Wings and Zaviga graphics is traslated 2-char left.

**Comment by dinkc64** [comment]
thanks, this is another akkaarrh_tilemap_fix collateral damage bug :) sorry guys

**Comment by dinkc64** [comment]
fastpop72, the fix is in, thanks again!

a while back we did a fix to the tilemap system for akka arrh's mirroring&clipping & flipping effect, and it ended up causing a lot of problems that didn't exist before in these games (squaitsa, botanicf, bagman, and these).  Tonight I backed it out and will explore a different/better path to fixing it soon!

best regards,
- dink

**Comment by fastpop72** [comment]
Tested! Now works again! Thanks!
