### ISSUE TITLE
hard dunk slow downs and jackie chan fist of fire problem in gfx

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1301]
i notice "hard dunk" have some slow downs issues and "jackie chan fist of fire" have problem in gfx of characters.

**Comment by barbudreadmon** [comment]
"hard dunk" is a sega system 32 game, performance issues are likely if you are playing this on a pi4.

"jackie chan fist of fire" board is not fully emulated in MAME and i'd suppose it is the same situation here

**Comment by kounabi22** [comment]
i recent install from experiment section of retropie "lr-mame" and those problem dont exist....

**Comment by barbudreadmon** [comment]
Yes, i know MAME is slightly faster at emulating sega system 32 games than FBNeo, and i know it does not run them full speed either on pi4, because it was confirmed by retropie users and as a matter of fact emulating those games is more demanding than emulating cv1k games without reducing cpu clock. Optimizing those games for low end devices is a rabbit hole, use MAME if you prefer.

For jackie chan, please be more specific, preferably with screenshots. I tested that game on both emulators and can't tell the difference.

**Comment by kounabi22** [comment]
https://www.youtube.com/shorts/ELtr-Gr8CBI

you can notice some flickering in life bars ,some glitch in the portrait of enemy in the top right corner, and in the 2nd match jackie moves have some glitches ..

**Comment by dinkc64** [comment]
@kounabi22 thanks for the video, the problem with jchan2 has been fixed as far as I can tell

best regards,
- dink
