### ISSUE TITLE
Service menu in Demon Front freezes

### ISSUE THREAD

**Issue by KamiLordus** [finalburnneo/FBNeo#1375]
For example first change of the difficulty level in the service menu works without problems. Entering the menu and changing the difficulty level again freezes the game.

Can it be fixed?
Ra 1.14 Fbneo latest
Win11 i7 8700k rtx 3070ti

**Comment by barbudreadmon** [comment]
I'm not sure it's a bug, MAME is having exactly the same behavior despite our pgm drivers not being ported from each other. Maybe @iq132 would know more about this ?

Furthermore there is no real problem here, the settings are correctly saved, and the emulator isn't freezing (you simply need to restart the game).

**Comment by KamiLordus** [comment]
On MAME, I was unable to reproduce this error.
This is probably due to the need to restart the system/game after saving changes in the service menu.
![Bez tytułu](https://user-images.githubusercontent.com/123302593/223703249-70ca5c60-0fef-4a5b-a425-38744d7e44c7.png)

Yes, manually restarting the game helps and it's not a big problem.

**Comment by barbudreadmon** [comment]
Weird, i have that behavior in MAME too, i'll try to investigate this a bit more.

**Comment by arcadez2003** [comment]
This might be protection related as they dont have a proper dump of the external MCU and are
using fake ARM7 stack commands to feed expected data from the external to the internal MCU.

Personally i've noticed weird behavour like you change the region to say English but you then get
a hybrid situation where the game flips between English and other languages totally at random
or you change the amount of lives and again sometimes the game starts with more sometimes
with less.

I kinda gave up on trying to change the game settings and took the view hey at least it works 
nowadays, as for years it wasn't playable until Haze found that exploit.

**Comment by arcadez2003** [comment]
Talking from memory really but fix or not until we have bona-fida dumps of both the interal and
external MCU's for Demon Front and many other PGM games we cant be sure of the emulation
of them.

**Comment by barbudreadmon** [comment]
@arcadez2003 FWIW, i think https://github.com/finalburnneo/FBNeo/commit/2e5354ce77aa41bc9ed6150024ca62d163d473c0 fixed that region issue you talked about. https://github.com/finalburnneo/FBNeo/commit/f71ab8db4eb5894c8cf515d6507e131b7f4c852c might also be somehow related.

Anyway i'll close since it's not entirely clear if the OP's report is a bug or not.
