### ISSUE TITLE
Opening FB Neo with an XInput controller connected takes longer than expected on certain systems

### ISSUE THREAD

**Issue by Ner0ls** [finalburnneo/FBNeo#1437]
This is a fairly common issue for many people just search "FBNeo takes too long" on google.

I discovered that this is related to having a controller connected to my system, it appears that something on FBNeo locks out when you have a controller connected (in my case an 8bitdo Pro 2 on X-Input mode), the debug console just gets stuck on "Enabling High Resolution Timer" but I'm pretty sure this has nothing to do with the bug, after a minute or so FBNeo opens, but if you disconnect the controller earlier it opens instantly.

Steps to replicate this (at least on my system) are: 
- Open FBNeo
- Close it
- Connect the controller
- Re open it

Just by doing this it triggers the bug. A workaround is to disconnect the controller, then re-connect it.

**Comment by dinkc64** [comment]
This is very strange, I have a ds3 using scp driverset which does xinput/dinput, but I also have several friends with 8bitdo gamepads, and neither of us have this problem.  Many moons ago I ran into someone with a similar problem, in the end it turned out their hdd(or sdd?) was failing, and moving things over to a new drive solved it.  I'm not suggesting that is the problem, but in order to fix something like this, I would need to be able to reproduce it on my pc or a pc in my possession, for debugging.

best regards,
- dink

**Comment by Ner0ls** [comment]
Is there any way to make the debugger more verbose? Maybe I could provide some logs but right now it doesn't give too much detail.

**Comment by Ner0ls** [comment]
So, upon further inspecting this issue, I concluded that this has nothing to do with FBNEO, Windows is acting up with the XBox 360 Drivers not behaving correctly on W10 for my specific controller (8bitdo Pro 2), my workaround was downgrading the driver into a Win7 64-bit version (2.1.0.1349) after that the issue was no more.

**Comment by dinkc64** [comment]
Glad you got it working! :)

best regards,
- dink
