### ISSUE TITLE
[LINUX, sdl / sdl2] make compiling, build non-debug release

### ISSUE THREAD

**Issue by cinnamonmatexfce** [finalburnneo/FBNeo#1445]
I noticed that standard compilation (`make sdl` / `make sdl2`) creates the *debug* version of the executable...
But I found this on `https://github.com/finalburnneo/FBNeo/tree/master/.github/workflows)/sdl2.yml.ignore`:
 - `make sdl -j9 RELEASEBUILD=1 SKIPDEPEND=1`

</br>

Is there any particular reason why - by default - the build is done in *debug* mode?

Also, can you please explain me what `SKIPDEPEND=1` actually is needed for? I don't understand this:
```
https://github.com/finalburnneo/FBNeo/blob/master/makefile.sdl2

# Check for changes in header files
ifndef	SKIPDEPEND
DEPEND = 1
endif

```
_________________________________________________________________________________________________________________________________________

(sorry if this is a noob question, feel free to close the issue)

**Comment by dinkc64** [comment]
My dear unpixelated cousin from Italy,
SKIPDEPEND is a thing that finds all .c/.cpp/.h files associated with each other and rebuilds them on subsequent makes.
So, let's say you make a change to burnint.h - which nearly every driver in the project uses... It will figure that out, and re-build every driver.  It's very slow, and actually quicker to just clean the object directory and re-make from scratch than to use it.  

I'm not too sure about why SDL build is making debug by default, but, I have a feeling it's because the SDL build isn't quite complete yet, and still in development.

best regards,
- dink

**Comment by cinnamonmatexfce** [comment]
Thanks for answering me. Have a nice day, dear unpixelated cousin! 😃
