### ISSUE TITLE
super toffy freeze screen after main screen

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1460]
when the game stoffy loads and it pass the main screen it just shows one mess screen of the game and nothing happends when you insert coins or press start.
if you are quick to insert coin and press start before the main screen pass then the game is playable.

**Comment by dinkc64** [comment]
@barbudreadmon can you see if this problem happens on your side?

**Comment by dinkc64** [comment]
Hi kounabi22,
The problem is with hiscore.dat, the Super Toffy entry needs to be changed from:
;(super toffy) (by GeoMan)
stoffy:
stoffyu:
@:maincpu,program,833,e0,00,f2
@:maincpu,program,913,a0,20,ff

to:
;(super toffy) (by GeoMan)
stoffy:
stoffyu:
@:maincpu,program,913,a0,20,ff

Here's the edited hiscore.dat file, just copy it over your current hiscore.dat file and delete stoffy.hi before loading the game.

[hiscoredat.zip](https://github.com/finalburnneo/FBNeo/files/11392120/hiscoredat.zip)

Would you be kind enough to email Leezer, the author of hiscore.dat, and let him know about this change?  His e-mail address is on the Hiscore.dat page: https://highscore.mameworld.info/

( I don't use e-mail, unless my life depends on it :)

best regards,
- dink

**Comment by dinkc64** [comment]
Hi kounabi22,
The problem is with hiscore.dat, the Super Toffy entry needs to be changed from:
;(super toffy) (by GeoMan)
stoffy:
stoffyu:
@:maincpu,program,833,e0,00,f2
@:maincpu,program,913,a0,20,ff

to:
;(super toffy) (by GeoMan)
stoffy:
stoffyu:
@:maincpu,program,913,a0,20,ff

Here's the edited hiscore.dat file, just copy it over your current hiscore.dat file and delete stoffy.hi before loading the game.

[hiscoredat.zip](https://github.com/finalburnneo/FBNeo/files/11392120/hiscoredat.zip)

It would be very awesome if you could email Leezer, the author of hiscore.dat, and let him know about this change - His e-mail address is on the Hiscore.dat page: https://highscore.mameworld.info/

( I don't use e-mail, unless my life depends on it :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
>changed from:
;(super toffy) (by GeoMan)
stoffy:
stoffyu:
@:maincpu,program,833,e0,00,f2
@:maincpu,program,913,a0,20,ff

Hmmm the current hiscore.dat entry looks more like this : 

>@:maincpu,program,833,e0,00,f2
@:maincpu,program,913,f0,20,00

So both lines are wrong and must be replaced/discarded ?

**Comment by dinkc64** [comment]
Yes, replace with the line in my post :)

**Comment by dinkc64** [comment]
@barbudreadmon could you please merge the new cv1k stuff? :)

**Comment by dinkc64** [comment]
thanks! :)
