### ISSUE TITLE
Namco System 86 Incorrect Refresh Rates

### ISSUE THREAD

**Issue by rtomasa** [finalburnneo/FBNeo#1476]
Hi,

I found that all Namco System 86 games run at 60 Hz by default.
Looking at d_namcos86.cpp, I don't see any call to BurnSetRefreshRate(XX);

The proper refresh for all games in this board should be 60.606061 Hz

Best Regards

**Comment by dinkc64** [comment]
we're not setting the refresh for anything over 60hz

**Comment by rtomasa** [comment]
I'm curious. Is this for compatibility reasons with LCD 60hz monitors?

**Comment by dinkc64** [comment]
yes.  I was thinking of a solution that will work fine for everyone: maybe a configuration option to tell the system it is ok to go over 60hz, or maybe query it somehow.   hmm

**Comment by rtomasa** [comment]
Maybe a new Capped 60 option? it could be set to ON by default so that if you disable the same and the forced 60 is also off it allows go over 60. BTW I was reporting this issue because I use FBNeo in CRT too which do not have such freq limitations.

**Comment by barbudreadmon** [comment]
@dinkc64 apparently, in windows, you can use https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-querydisplayconfig, it's not available before windows 7 though.

As for the libretro port (which @rtomasa is using ?), my understanding is that it should always be allowed because the frontend will reduce refresh rate anyway if the display is not compatible

**Comment by rtomasa** [comment]
Yes I'm using the lr core. Sorry for not mentioning that before.
Retroarch has some logic similar to the one you mentioned but the reality is that it seems that is does not really apply when the real refresh rate is natively over 60 (in CRT). Maybe it is the VSYNC that forces to speed up the thing.

```
/* Roundings to PAL & NTSC standards */
if (video_st.refresh_rate_original > 54 && video_st.refresh_rate_original < 60)
    video_st.refresh_rate_suggest = 59.94f;
else if (video_st.refresh_rate_original > 49 && video_st.refresh_rate_original < 55)
    video_st.refresh_rate_suggest = 50.00f;
/* Fallback when target refresh rate is not exposed or when below standards */
else if (video_st.refresh_rate_original < 50)
    video_st.refresh_rate_suggest = DEFAULT_REFRESH_RATE;
```

**Comment by barbudreadmon** [comment]
that logic might have to do with retroarch's behavior when their [vrr_runloop](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#music-is-high-pitched-too-fast-andor-different-from-fbneo-standalone-why-) is disabled.

**Comment by barbudreadmon** [comment]
So i asked and here is how retroarch *apparently* handles this : 
- if VRR is enabled in settings, it will match whatever the core is asking for refresh rate, if the monitor is unable to handle those refresh rate it will accordingly dupe/skip frames, if the monitor can handle it (crt, g-sync and freesync ?) then everything is fine and the content will run at the correct refresh rate without any kind of dupe/skip
- if VRR is disabled, it will try to match monitor capabilities, slowing down or speeding up the framerate
 
I'm considering 2 changes : 
- it's possible to fetch the monitor's refresh rate using libretro's api (it's basically using the function i mentioned above) so to minimize tearing it might be interesting to have an extern variable or function to get that value and use it instead of the current hard-coded 60Hz for our "force 60hz" setting
- using an extern variable or function to determine if the frontend is ok with 60+ Hz refresh rate (it would always be true in the case of libretro port, since it's considered "best practice" to let the frontend handle the final decision according to VRR setting and monitor capabilities; not sure what to do for standalone, i suppose it could be set to false until we are confortable with that change)

**Comment by rtomasa** [comment]
That totally makes sense to me.

**Comment by dinkc64** [comment]
For best compatibility - perhaps just make a burn.cpp global variable like bSpeedLimit60hz, if its not true then use > 60.
Then in the fbn ui, add an option "Monitor capable of > 60hz"

**Comment by dinkc64** [comment]
p.s. any idea why the cores on the libretro buildbot havn't updated since the 15th?  Got a friend who is very eager to try some new fbneo code :)

best regards,
- dink

**Comment by barbudreadmon** [comment]
it seems building mame killed their buildbot somehow : https://git.libretro.com/libretro/mame/-/pipelines

**Comment by barbudreadmon** [comment]
>Force 60hz, hmm, I think this should override any other setting if it's enabled.

The thing is that my monitor is running at 59.95Hz with my current resolution (i can use 60Hz at other resolutions), so that's probably the freq i'd like to force if i wanted to ignore correct refresh rate.

**Comment by dinkc64** [comment]
Regarding the hz stuff, what a headache :)

Good luck on your trip, see ya when you get back!

best regards,
- dink

**Comment by petran79** [comment]
I use a Gsync chip monitor and there is an issue even with games at 60 hz or below too, eg Mortal Kombat 1 credit screen and Samurai Showdown 2 shadows are not as smooth as intended. I notice even SNES games have issues, eg on Tiny Toons SNES game, the dash bar does not flicker as fast as it should
Only way is to use Retroarch finalburn instead of the stand alone version. On standalone there is also the shader issue where each game and console requires different shaders to appear correctly.

**Comment by barbudreadmon** [comment]
I'm not too sure how this gsync/freesync stuff works, but it might be that it requires some specific software code that is not implemented in our standalone ?

**Comment by petran79** [comment]
I think it mostly requires support of exclusive fullscreen as it activates automatically

**Comment by dinkc64** [comment]
I won't be able to afford such nice things like freesync/gsync, so, it won't be possible for me do do anything with this.
