### ISSUE TITLE
Sega system 32 close retroarch

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1507]
Hello
In retroarch the Sega system 32 games don't work, when I open every game, retroarch just closes.
Please fix it thanks

**Comment by barbudreadmon** [comment]
Thanks for the report

@dinkc64 it appears to be collateral damage from the timer update, it's crashing on https://github.com/finalburnneo/FBNeo/blob/6e5edec97bea946eeae6bc8fcecd639a4af59726/src/burn/drv/sega/d_segas32.cpp#L4409
I tried fixing this by myself, but ended up with no sound at all.
I'm sort of surprised though: since juan mentions retroarch, does it mean the crash doesn't happen on standalone ?

**Comment by KamiLordus** [comment]
Sega System 18 also crashes.
I'm trying to run Shadow Dancer, and it's the same as in the first post.
retroarch 1.15
Win 11

**Comment by dinkc64** [comment]
thanks guys, will have a look :)

**Comment by dinkc64** [comment]
problem solved, thanks for letting us know!

That timer change was huge, a little collateral damage is to be expected, but also easy to fix :)

best regards,
- dink
