### ISSUE TITLE
[Libretro] When Rewind  & Run Ahead are both enabled, Rewind fails

### ISSUE THREAD

**Issue by roslof** [finalburnneo/FBNeo#1535]
[EDIT: A clearer repro is listed in comments below]

Tested on a Raspberry Pi4B with a current build of lr-fbneo (5ff066c).

ISSUE: Using RetroPie and having the Rewind feature turned on [enabled] at launch, engaging rewind may result in one of these bad behaviors:

1. A reset of the game
2. A crash of the game, exiting
3. A freeze of the game, requiring a remote kill to exit libretro

Note: If the rewind feature is NOT enabled at launch, and manually enabled via core options, rewind works properly.

STEPS TO REPRODUCE:
1. Enable Rewind via libretro settings and save configuration (or simply modify the retroarch.cfg file to enable rewind.
2. Rewind settings do not matter. Default values of 1 rewind frame, 20 buffer size, and 10 size step are fine.
3. Load "Donkey Kong" (any romset)
4. Engage rewind at any time
5. Donkey Kong will reset instead of rewind

Again, if step 1 is "Disabled" and the player manually enables Rewind, rewind will function correctly. Issue is specific to rewind being auto-enabled at the same time fbneo launches.

I'm not certain which build started yielding the issue, so this issue may have been introduced within short days to several months ago.

As always, I hope this information is useful to the project.

**Comment by roslof** [comment]
https://github.com/finalburnneo/FBNeo/assets/6511782/bbe5bbf9-2adf-4401-b143-43f7827acddd

Attached video shows rewind being engaged during the intro of Donkey Kong when Kong climbs the ladder. This is performed twice, with the result being a reset of the game.

**Comment by roslof** [comment]
Issue left on incorrect github. Closing.

**Comment by barbudreadmon** [comment]
I can't seem to reproduce this at all on dkong, so i don't think that's a FBNeo issue ? Maybe something setup related ?

**Comment by roslof** [comment]
Thank you @barbudreadmon. I posted more details in the [RetroPie Forums](https://retropie.org.uk/forum/topic/34453/rewind-issue-with-retropie-fbneo) that helped narrow down a repro. Issue occurs when rom .cfgs contain:

rewind_enable = "true"
run_ahead_enabled = "true"

The issue occurs.

**Comment by barbudreadmon** [comment]
Hmmm ok, i can reproduce this and i know what this is about.

The retroarch logic when using multiple savestate-based features is flawed, because it requests and store savestate size only once for the 1st savestate context being used, instead of requesting and storing multiple savestate size when multiple savestate context are being used.

Rewind and runahead are 2 different savestate context with different savestate sizes, which is messing things. It seems to only be a problem if the smallest size is queried first.

Well, technically it is a retroarch bug, but let's leave it open here since i'll most likely be the one working on this. I am not entirely sure any core use this aside from FBNeo anyway.

It's my bad for overlooking this when i wrote the apicall to leverage retroarch's savestate context awareness. Well, i suppose it was already flawed with their fast savestate workaround thingy i used before implementing that stuff.

**Comment by roslof** [comment]
Okay... I dug even deeper and it appears this is not .cfg specific. Simply put, if both run_ahead and rewind are enabled at the time the game launches, rewind will fail.

There are two (2) ways to reproduce the bug w/dkong:


1. In RetroArch (or by modifying retroarch.cfg) enable both Latency/Run-Ahead to Reduce Latency and Frame Throttle/Rewind/Rewind Support. Ensure game launched does not have an override. Save... Launch dkong

or

2. Edit a rom .cfg override and set both rewind_enable = "true" and run_ahead_enabled = "true". Save. Launch dkong.

Then try rewind. Results should be the same as in my video above.

**Comment by barbudreadmon** [comment]
Hehe, that issue ringed a bell and it turned out i pushed a workaround for it last year (https://github.com/libretro/FBNeo/commit/b50b9d144b63f006cdd7334d300eab7631279426 and https://github.com/libretro/FBNeo/commit/4a1d9329e3b1796916ffb906ab62eea95f1feae6), but i think someone noticed the flawed logic in retroarch and fixed it properly after that, and that very same fix broke my own workaround.

The good thing is that removing my workaround seems to fully solve the issue, so nothing to do aside from doing that and hoping nobody still uses last year's retroarch version with the flawed logic.

**Comment by barbudreadmon** [comment]
This is about using different savestate content for different savestate context (standard savestates, netplay, runahead, 2-instance runahead), which is a required optimization when you try to push runahead & netplay support to the next level. It doesn't have anything to do with determinism or size fluctuation, and afaik determinism and size fluctuation don't exclude each other anyway.

**Comment by barbudreadmon** [comment]
>Since you removed it it looks right now.

Yeah, again, that was a workaround for the old flawed logic in retroarch (one savestate size to rule them all), and it shouldn't be kept if the real problem was fixed. I'm still a bit concerned that savestate size can't fluctuate within the same context, i don't understand why it should be a requirement because iirc runahead works just fine with fluctuating savestate size (cv1k) in standalone, but things seems to be at least better than they used to be.

**Comment by barbudreadmon** [comment]
>There is no reason for it to fluctuate that I can think of.

There are reasons, sometimes the exact required size can't be determined at init (ex. cv1k's serial flash), meaning your savestate size will fluctuate.

**Comment by dinkc64** [comment]
Well at least MistyDreams finally knows what a hack is :)

**Comment by barbudreadmon** [comment]
>I dont see how the flash would effect the save file size.

Because the flash is serialized within the savestate.

**Comment by barbudreadmon** [comment]
>Ah so its fixable just just some savesate juggling

I don't understand what you mean, the savestates are fine like that.

**Comment by barbudreadmon** [comment]
>The savefile shouldnt be changing size

Again, this is only a decision made arbitrarily in retroarch, it has nothing to do with determinism, and afaik runahead works perfectly fine in standalone with fluctuating savestate size.

>Surely the flash is a fixed size

Every cv1k game has a different serialized size for that device's state if that's what you are wondering about.

**Comment by dinkc64** [comment]
States also change size in MAME for cv1k, NeoGeo pocket/pocket color and some other systems.  They change in relation to the blocks written to the flash.  It would be impossibly slow for runahead/rewind to work if we just scanned the entire flash rom.

**Comment by roslof** [comment]
Issue confirmed fixed with libretro fbneo changelist [de5055c](https://github.com/libretro/FBNeo/commit/de5055c907e0cf0abb8ad8dc31ef550fcbc62a6e).

**Comment by dinkc64** [comment]
Hooray! :)
