### ISSUE TITLE
(libretro) Dip switches bios (fronted menu problem)

### ISSUE THREAD

**Issue by hatetepe** [finalburnneo/FBNeo#1632]
The fbneo libretro version has a small but annoying bug.
Changing the BIOS in dip switches (no matter which one) does not return to the BIOS options, but goes down to the memory card.
This happens every time I start the game and try to change the bios.
Strangely enough, if I try to change the bios a second time (without turning off and restarting the game), everything is fine.
It's a bit bothersome because I'm creating my game list using Fb Neo and I often change the bios.

**Comment by barbudreadmon** [comment]
>Changing the BIOS in dip switches (no matter which one) does not return to the BIOS options, but goes down to the memory card.

Sorry but i have absolutely no idea what you mean. I think you'll need to provide a video or something.

**Comment by hatetepe** [comment]
Sorry, I'll try to be more specific:

When I change the bios for the rom here:
![Zrzut ekranu 2024-01-08 215912](https://github.com/finalburnneo/FBNeo/assets/130509159/c1b306d0-7808-474f-bd66-14b57efca223)


Fronted index no return to bios but automatically jumps down to memory card.
![Zrzut ekranu 2024-01-08 220330](https://github.com/finalburnneo/FBNeo/assets/130509159/f15adb38-1429-4a9e-8a26-0b4d1653f5f8)


I noticed one more thing. This only happens once, as I have already mentioned, and when there is no previously changed and saved BIOS configuration for a given game.

**Comment by barbudreadmon** [comment]
Ok, well, strictly speaking, this is frontend behavior, the core doesn't choose which core option is selected in the frontend.

However it is probably originating from the "coin chutes" dipswitches, and i think their dynamic visibility (many core options are dynamically visible) is behaving wrongly, so i'll take a look soon.

**Comment by barbudreadmon** [comment]
So yeah, i was right, there was a bug about the 2 "coin chutes" dips being visible at boot. It is fixed with https://github.com/libretro/FBNeo/commit/4138e7d4f949780f4176f6c174177eb3b6cc2789.

It *should* prevent retroarch from moving the core option cursor since now the list of core options doesn't shrink anymore after changing bios. Please note that there might be other cases where a growing/shrinking list can't be avoided, in which case retroarch will still have that behavior and there won't be anything possible to avoid it on core's side.

**Comment by hatetepe** [comment]
Thank you for solving the problem.
