### ISSUE TITLE
Violent Storm

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1652]
After defeating 1st Boss, transition to the next stage is to bright, actualy this transition is wrong for all game, and after defeating 2nd Boss fire works are washed out and there's a big square on half of the screen showing up in timing with the fire works effect, mame have the same but in mame the box have color of the fireworks effect (pink/purple) non of that is present in real hardware.

**Comment by BilonFullHDemon** [comment]
FBneo - stransition to next stage - 4:54 to 4:58 https://www.youtube.com/watch?v=GzPTDyKR9A4
FBneo - fire works - 8:09 to 8:14 https://www.youtube.com/watch?v=GzPTDyKR9A4

Real Hardware - transition - 3:07 to 3:10 ( it fades to black and from black on new stage) https://www.youtube.com/watch?v=-27XhdEXAyU
Real Hardware - fireworks - 6:25 to 6:28 ( fire works blast have different collor each )

**Comment by dinkc64** [comment]
Patience, friend, I'm just 1 person fixing these difficult things!
Will look into it as soon as possible

**Comment by BilonFullHDemon** [comment]
Take your time, I just wanted to know is it fixable.Thank you all for all the hard work

**Comment by dinkc64** [comment]
Hi,
Some good news so far: The screen fades and fireworks colors are fixed  :)

I will attempt to fix the fireworks color-box that covers the right-half of the screen tomorrow, and post the code on github

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Wow, you are a wizard, thank you!

**Comment by dinkc64** [comment]
Here's a little "progress-so-far" video
https://www.youtube.com/watch?v=GFhM9cuUIfI

The red stuff on the right side ended up being a shadow mask (for the fadeouts) which didn't get de-prioritized.  I'll review and commit the code after a good night sleep :)

best regards,
- dink

**Comment by dinkc64** [comment]
A little info on the fixes:

First fix is for the fading, this bug was caused by a typo when I implemented the shadow bank support - oops :)
Second fix is for the "half screen is red" during fireworks, when the screen fades out/fades in, the game covers both sides of the screen with a big rectangle sprites, for some reason, the game leaves the sprites active from the previous fades (end of level 1), but they're fully transparent so you don't know they exists... 
until the shadow masking of the fireworks kick in and colors it red (or later yellow).  

Do you want to play the game to the end to see if any more gfx issues come up? :)

best regards,
- dink

**Comment by BilonFullHDemon** [comment]
Thank you! amazing job! now I can rest in peace XD

**Comment by dinkc64** [comment]
you're welcome :)

**Comment by dinkc64** [comment]
as a bonus, Metamorphic Force got a few gfx fixes as well :)
While it isn't perfect yet, it's a lot "less worse" or "more improved" than it was,
Titlescreen got fixed
Level 1 boss "evil ring" prioritys fixed
Also light coming in the window in the end level is half-fixed: it looks like light now, but it doesn't shine on the sprites (just the background)

best regards,
- dink
