### ISSUE TITLE
Standalone FBNeo does not start the game in Kaillera netplay (Couldn't create main window)

### ISSUE THREAD

**Issue by Fatih120** [finalburnneo/FBNeo#1662]
![image](https://github.com/finalburnneo/FBNeo/assets/18276369/03210345-1331-467d-a8e4-19cef390e7b2)
I have been planning to play some shmups with my friend, such as futaribl and ddpsdoj, which work just fine playing alone, but when I try to play online and pick any server and /start the session, both of us encounter the error above with no other explanation. When I leave the server, the following is displayed:

![image](https://github.com/finalburnneo/FBNeo/assets/18276369/217dc9a3-c638-41e4-a979-ad844ead4697)

FBNeo proceeds to either hang or crash shortly after another dialog, and I manage to see this from the log, though I'm not sure how useful it is:

[FBNEO.txt](https://github.com/finalburnneo/FBNeo/files/14149460/FBNEO.txt)

We are both using 1.0.0.03 nightly releases around this time, and we both downloaded 0.89.10 of https://github.com/God-Weapon/SupraclientC in the install directory next to the executable - perhaps this isn't what we're supposed to be using? I could not find anything about this online and in my ignorance this could be a low-level human error.

**Comment by dinkc64** [comment]
Hi,
I tested it with the old 32bit kaillera dll and current fbn exe and ddpsdoj plays well between 2 pc's.  I'll try to figure out what is going on with fbn & SupraclientC.  In the meantime, if you and friends want to use the 32bit version of fbneo & the old kaillera dll, here's the file:
[kaillera.zip](https://github.com/finalburnneo/FBNeo/files/14150164/kaillera.zip)

best regards,
- dink

**Comment by dinkc64** [comment]
Thanks! :)
I'm glad it's working out, the past couple days I've been trying to improve the kaillera code - one thing that always bothered me is that the emulator becomes very unstable after a game of kaillera, that's fixed now - and SupraclientC works as well :)

There's only one problem, but it's inherent to SupraclientC - the client drops packets sooner or later, and this completely ruins the netplay synchronization - thus ending the game.  I had a look at the source code of this client, and it appears that its not properly dealing with out-of-order packets.  It's a shame, because this client has such a nice interface.

I'll post back here when the new kaillera-support code makes it into github, need to do a bit more testing before I merge it.  Hopefully it'll be later today :)

best regards,
- dink

**Comment by dinkc64** [comment]
The fixes/update made it in :)

**Comment by dinkc64** [comment]
Just curious, did you try the SupraclientC Kaillera?  Did you get any dropped packets during a game?

best regards,
- dink

**Comment by Fatih120** [comment]
I have only played a session with my friend using the old Kaillera with 32bit FBN - have yet to test using SupraclientC ourselves, which I figure we should do once I can rope us into a good time. I'll try to provide an update whenever possible, hopefully testing through with a few different types of games and connections.

**Comment by Fatih120** [comment]
Even though it's very late, I just wanted to say that lately we finally got a chance to play several games using SupraclientC on one of the recent nightlies and it's been a good experience. No dropped packets.
