### ISSUE TITLE
backfire! clone rom support?

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1687]
Dont know if you can add clone rom of backfire ---> backfirea

**Comment by barbudreadmon** [comment]
Hmmm the clone has been present in our source code for a very long time but flagged as non-working for some reason. There is also some weird comment about having to set the inputs to joystick in service mode but it's apparently the default.

It *looks* fine, i can't really say much more since i absolutely sucks at that kind of racing game, maybe dink know of some issue explaining it's flagged as non-working ?

**Comment by dinkc64** [comment]
needs analog inputs hooked up before we do that

**Comment by barbudreadmon** [comment]
the game seems playable with the 8-way stick though ?

**Comment by dinkc64** [comment]
I've added it (locally), but it is unfortunately very buggy :/  In the service mode it's positional, but go to the game, and the wheel is unsynchronized...

Might be better to try to get the optical to work, its probable a simple quadrature

**Comment by dinkc64** [comment]
DERP!  
It just needed calibration :)

**Comment by dinkc64** [comment]
Hi,
set #2 (backfirea) was added, along with analog wheel input
note: set #1 defaults to 8-way joy, set #2 defaults to analog wheel

best regards,
- dink

**Comment by dinkc64** [comment]
@barbudreadmon, the game is almost unplayable with 8way joy, its almost like it was made for analog wheel, but the 8way joy was an afterthought to support old cabs without a wheel

**Comment by kounabi22** [comment]
in the 2 screen mode the 2nd player coin button is not working...you can get coins by pressing left analog stick up.

**Comment by dinkc64** [comment]
fingers crossed, it should be good now :)

hopefully!

best regards,
- dink

**Comment by kounabi22** [comment]
ty all is ok.
