### ISSUE TITLE
Are these hacks really good?

### ISSUE THREAD

**Issue by SumavisionQ5** [finalburnneo/FBNeo#1726]
I found that recently some HBMame hacks have been inclueded into FBNeo (see: https://github.com/finalburnneo/FBNeo/issues/1715), and honestly speaking, those hacks are not fantastic. 
They are poorly hacked, and some of them are really boring. 
If anyone want to play those hacks, he can run them with IPS on Windows platform or run them by putting the patched version of the romset into SYSTEM_DIRECTORY/fbneo/patched with RetroArch on other platforms.
I've no intention of offending anyone, but I think FBNeo should be more strict with hacks.
Even now, HBMAME stops to include cheap hacks. 
FBNeo has many ways to run hacks, so we should not expand game library too prematurely.

**Comment by taoenwen** [comment]
Thank you for your suggestions, good intentions don't offend anyone.

In this regard, we might as well listen to more voices as well, and if there is a consensus, we will certainly take it on board.

**Comment by dinkc64** [comment]
well, not everyone has same taste, also NeilDark is a respected user
best regards,
- dink

**Comment by Neildark** [comment]
By allusions, and also to explain my criterion, when I requested that these hacks be included, I would like to comment on some things, and excuse me for my poor English: in the taoenwen repository, https://github.com/taoenwen/FBNeo_IPS, which could be considered the official one for Final Burn NEO, there is no IPS for the games I added, there were no hacks for World Heroes 2, Word Heroes 2 Jet, Fatal Fury 2, Fatal Fury Special, Fatal Fury 3, Marvel Super Heroes Vs. Street Fighter, X-Men or Hyper Street Fighter II: The Anniversary Edition.

For fans of fighting games, as is my case, the Easy Moves trick, which is what I have chosen, is very necessary to do TAS and tests for bugs and curiosities in games that are then uploaded to YouTube, and I think it is very interesting especially in old games, and also to introduce the emulator. I'm aware that there are MAME IPS that could be used for this very thing, but not everyone has the time to find and manage them, and they don't always work.

As for Hyper Street Fighter II: The Anniversary Edition (040202U, 30% Blood) and fixed difficulty) (hack 2024), it is chosen because it is a very complicated game for new players and those two tricks help a lot to enjoy the game, the First, it reduces the damage of the hits and second, the difficulty, which, by the way, is a huge mistake in the original game because changing it has no effect.

HBMAME has more than 8,000 hacks, I don't think it's very strict, especially because it has many repeats, updated without removing the previous ones, some don't even work, etc. In my opinion, I think that FBN has the opportunity to filter the most interesting hacks, according to the criterion of all users, and try to give new life to old games. If you are not a lover of fighting games (Neo Geo), you may think that, for example, having 29 KOF97 hacks is excessive, but Cadillacs and Dinosaurs has ¡¡¡30!!!

This being the second time that I request that hacks be added here, I think that is the policy that has always been followed, and for my part I am happy that it is so. I think they add new life to the game and anything that makes it easier to access them is the best solution, so, without overdoing it, I would like to continue suggesting new hacks later, naturally not for simple accumulation.

Naturally it is my opinion, and it is always pleasant to debate and contrast points of view, ¡greetings to all and thank you for your work!

**Comment by barbudreadmon** [comment]
I'd say "Super Street Fighter II Turbo (940223ETC, difficulty fix) (hack 2024)" is arguably a hack i didn't want to see added.

If i'm not mistaken, this is based on a cheat i have seen posted somewhere (MAME's subreddit ?) a few months ago, porting this cheat to FBNeo format might have been the better choice imho.

**Comment by taoenwen** [comment]
Previously limited by my own time and energy, I stopped for a few months, and recently I'm going to restart the IPS project and prioritize some of the requests from users (who may have them), in the form of IPS, so that people can test it more and get consensus feedback before moving on to the later step.

**Comment by taoenwen** [comment]
If there is a consensus emerging from the exchanges and no one has any new comments or suggestions for a period of time, I will take that as a willingness to agree on this, thank you for your participation and love, and I wish you all the best!
