### ISSUE TITLE
Possible rights grant (license) violation

### ISSUE THREAD

**Issue by RogueScholar** [finalburnneo/FBNeo#1751]
This is more of a project management concern than a proper bug report, but while compiling FBNeo from source today I had a handful of spare moments, and as I often tend to do in those I opened the [repository's license file](https://github.com/finalburnneo/FBNeo/blob/master/src/license.txt) in my pager to have a look around and make sure I wasn't violating it in practice or in spirit. First I want to commend you all collectively for one particular clause that resonates quite deeply with me, namely:

https://github.com/finalburnneo/FBNeo/blob/f97bbeac9571015b72bcf2919c6bc9f78abd71ea/src/license.txt#L7

I've long-felt that open-source projects are getting sucked into the bleak hell-scape that is late-stage capitalism as practiced in most of the major Western societies. Unless the project is consumed by large, for-profit enterprises or is of such grand scope and broad utility that it would be untenable absent full-time developers, my personal belief is that we should all put food on our table in our own time. Once that's attended to, whatever remaining time we see fit to devote to open source software should (ideally) be performed in the spirit of true generosity, and without all of the constant calls to action that link to donation pages and insidious exhortations to buy us a beer or a coffee. If the goal is to eventually have a society where we each do what we love, for no reason other than it giving us a sense of purpose, then it has to start by acting that way even before we get there. That's what I believe, at least, but I digress…

My concern stems from the mention in the README of a downstream fork by the Libretro project. (Which, in the interests of transparency, I have contributed code to in the past, myself.) I find that their approach is rather at variance with mine in spirit when it comes to how open source projects should support themselves, since they certainly have abandoned any shyness about asking for [donations](https://www.retroarch.com/index.php?page=donate). I'd find that many highly-visible attempts to monetize a collective effort distasteful on its face, but weighed along with the objective lack of transparency over how those funds are allocated and the primary developer's [well-earned reputation](https://github.com/ekeeke/Genesis-Plus-GX/issues/111) for being abusive and manipulative, I view them now with a great deal more skepticism than I once did.

To be clear, I don't have the slightest interest in sharpshooting how you run your project and if, as a development team, you've seen fit to furnish the Libretro guys with explicit license grants above and beyond what are published here, I fully respect your prerogative to do so. I raise this concern here on the chance that you were not aware of these behaviors, or that at the time of the downstream fork event, they were operating with more noble sentiments that aligned with your license and you simply haven't reevaluated things as circumstances have evolved.

Thanks to all of the developers to this project for not just their hard work but also their sense of ethics and propriety. 🤝 BTW, my compilation was successful on the very first run and not overly "noisy" either; I wish a much greater proportion of my builds were similarly well-behaved. 😆

**Comment by dinkc64** [comment]
The libretro core of FBNeo is under the exact same license as this.  As I understand it, Retroarch is asking donations for their project, the cores are a completely separate entity.

**Comment by barbudreadmon** [comment]
Some time ago i discussed it with kev and we agreed on this about the libretro port : 
* **"Redistributions may not be sold, nor may they be used in a commercial product or activity."** : By definition, a commercial activity is an activity involving the sale of goods or services. The libretro project does none of that, and it is unclear whether a patreon should be treated as a commercial activity or not when no goods or services are provided in exchange of the donations.
* **"You may not ask for donations to support your work on any project that uses the FB Neo source code."** : This FBNeo port is using libretro code, not the other way around. This port is directly authored/maintained/supported by members of the FBNeo team, and none of them is receiving donations. Interestingly, if receiving donations was de facto a commercial activity, this term shouldn't be required.
* *If* the libretro project was a commercial activity, it would still be unclear how it does affect this port. Our win32 standalone builds use the directx api, which belongs to a commercial company. Using the libretro api, which would belong to a commercial activity, wouldn't be any different. Furthermore, in all likeliness, there would still be alternative libretro frontends that don't belong to the libretro project and are not commercial. 
* Actually, alternative commercial libretro frontends already exist, and we consider we are not concerned as long as this port is not distributed with/through them and they don't use its availability as some mean of advertisement. In this scenario, only a manual installation of the core by the user will be considered legal and supported.
* While GPL code can't be mixed with non-commercial code, this is a non-issue since this port doesn't contain any GPL-licensed code.
* Under european law, where the libretro buildbots are located, linking GPL and non-commercial softwares doesn't produce a derivative work, and doesn't extend the GPL license to the non-commercial work (source [here](https://joinup.ec.europa.eu/collection/eupl/licence-compatibility-permissivity-reciprocity-and-interoperability)). It is unclear whether the same applies in non-EU countries or not.

Meaning there is no licensing issue we are aware of.

We do this for the users, not for the guy you are talking about. Furthermore, i still remember people doxxing that guy while talking about beating him on a certain discord server, so i think a lot of people should look in the mirror before calling him toxic/abusive/manipulative.

**Comment by tmaul** [comment]
Unless someone is going to pay for a fully qualified legal person to go over the licence in detail and work out exactly what is and isn't allowed, all we can do is complain to the many people who directly sell commercial products that have FBNeo as part of its core functionality (and there are many). 

The reality is all those people ignore us when we ask for the non-commercial part of licence to be respected (fightcade, the Barry stick, that shit pgm switch game, etc) and IF somehow the libretro port were breaking the licence I'm sure we would also be ignored. A licence is just a load of writing if you have no moral standing about ignoring it and there are no legal consequences in doing so.

**Comment by barbudreadmon** [comment]
>IF somehow the libretro port were breaking the licence I'm sure we would also be ignored

They have been willing to accomodate until now, a few years ago i asked for the license to be explicitly written in their online updater, and they abided. 
The port itself doesn't break the license, but its availability through their online updater *might*. If a fully qualified legal person confirmed this, it might be possible to provide our own builds through our own buildbot instead (it has been done for a few cores), not that i'm looking forward to this since it would cause frictions with many users (i have zero interest in setting up android/apple/console buildbots, especially apple where you apparently need to pay a subscription to sign binaries).
