### ISSUE TITLE
amidaru is upside down

### ISSUE THREAD

**Issue by grant2258** [finalburnneo/FBNeo#183]
Came across this when testing something on the sdl port. Sorry i dont have the full sets or i would have tested them all. Ill build the full set tonight when I get time tonight.

**Comment by dinkc64** [comment]
It's OK in win standalone, lets see if @0xe1f  can help with this, the game is in burn/drv/galaxian/d_galaxian.cpp with the
tags: BDF_ORIENTATION_VERTICAL | BDF_ORIENTATION_FLIPPED

**Comment by grant2258** [comment]
it was on stand alone i was testing it in maybe i have a bad option set ?

**Comment by 0xe1f** [comment]
I tested the SDL build on both macOS and Pi, but was unable to reproduce the bug. Both the experimental renderer (on Pi) and the software renderer (macOS) render as expected.

I am seeing screen corruption on the Pi build, similar to the effect from the Rygar bug (#170), and will look into it, but the SDL build is unaffected - looking at @grant2258's [pastebin log](https://github.com/finalburnneo/FBNeo/issues/183#issuecomment-559900662), seems like the bug is on Windows specifically.

**Comment by grant2258** [comment]
It seems if i change my blitter to  experimental (dx9) its all good

**Comment by dinkc64** [comment]
Oh, I thought you mentioned sdl port..  anyways, yes, the basic blitter relies on hw flipping and newer video drivers don't have hw flipping in directdraw support any longer in the I'm afraid.  Stay away from those vs/64bit builds though, they've got issues :( (other than this)

best regards,
- dink

**Comment by grant2258** [comment]
thanks for the info will close this one for now.
