### ISSUE TITLE
Mouse to Rotary support in knob/spinner games on Mac/iOS/iPadOS

### ISSUE THREAD

**Issue by MukiEX** [finalburnneo/FBNeo#1841]
A had a whole issue written out before realizing it worked just fine on my Windows machine.

Rotary games on F3, like Puchi Carat and Arkanoid Returns don't recognize mouse movement... on Mac/iOS/iPadOS, though in the latter 2 a mouse wouldn't work at all, as it only moves a finger cursor. That said, on both, touching the screen doesn't get recognized as mouse movement. This happens even when setting the controller to "Mouse (ball only)" or "Mouse (full).

In all three cases, a different core (PlayStation, I used Beetle HW with "Playstation Mouse" set as the controller) does seem to have this functionality with ports of the same games. I'm not even sure if this falls within the scope of the FBNeo project itself, however, or if it's a bug on RetroArch's end, so please feel free to close if this is, in fact, the case.

**Comment by barbudreadmon** [comment]
>A had a whole issue written out before realizing it worked just fine on my Windows machine.

If it works on windows but not on macosx with the same libretro port, then i can only suppose it's either a retroarch bug or a setup issue, you'll have to contact them about it.

Retroarch sends X/Y axis movements for mouse devices, kind of like an analog stick, a touchscreen is a different kind of device where retroarch sends coordinates. We have multiple device types working with coordinates (pointer, touchscreen, lightgun), however their usage is limited to the simulation of lightguns in gun games. To support this, either the frontend would have to send X/Y axis movements when a mouse device type is selected but a touchscreen is used, or the core would have to do that conversion when coordinates are sent but X/Y movements are expected. I'd certainly prefer the former since the current input code is already quite a mess due to all the lacks of retroarch's remapping, plus it'd benefit all cores.
