### ISSUE TITLE
Where do i put the roms on the raspberry pi port?

### ISSUE THREAD

**Issue by mateusrangel** [finalburnneo/FBNeo#1852]

**Comment by mateusrangel** [comment]
@0xe1f

**Comment by barbudreadmon** [comment]
I think the sdl port uses a fbneo.ini file and that's where you set things up.
Either way, the guy you pinged as an afterthought after opening an issue without any text hasn't answered to pings for a very long time, so i highly doubt he is going to answer you.

Also note that it is apparently recommended to avoid the sdl port and to use the libretro port instead, since the performance of the sdl port is apparently terrible.
