### ISSUE TITLE
Question: Any way for sdlk code works?

### ISSUE THREAD

**Issue by Ninoh-FOX** [finalburnneo/FBNeo#1865]
I have compiled as I said before the code for Raspberry Pi using the makefile.sdl2 with success.

Now, modifying the makefile.sdl to make cross compilation and do not use video gl I have compiled the binary with success so that it works on ARMHF consoles with success, but the controls do not work, only the Menu key (SDLK_ESCAPE) that closes the emulated.

Is it possible to make the SDLK keys work for P1 controls?

**Comment by barbudreadmon** [comment]
Make sure the path to your romsets is set for the `szAppRomPaths[0]` variable in `~/.local/share/fbneo/config/fbneo.ini`. You'll also need to delete `~/.local/share/fbneo/config/roms.found` so that the romset database is refreshed.
Afterward, launch the emulator again and it should be *functional enough* to allow you to navigate the game list and launch them.

As previously stated, don't expect too much from this sdl port, afaik the performance is bad and it might still be missing some important features. You probably shouldn't be using this if you already have the libretro port running.

**Comment by barbudreadmon** [comment]
For more instructions, read https://github.com/finalburnneo/FBNeo/blob/master/README-SDL.md

**Comment by Ninoh-FOX** [comment]
The games are not the problem, they all load fine and I don't even know if they are more fluid than RA, but the only problem I see is that none of the buttons work (menu is not available in sdl 1.2 version) so I can't even map it and I can't find any clear reference in the code.

**Comment by Ninoh-FOX** [comment]
I talk about Miyoo consoles or similars

**Comment by barbudreadmon** [comment]
>in sdl 1.2 version

Pretty sure i told you to use sdl2 version.
Well, i'm not a maintainer of those sdl port, and afaik the maintainers for those are mostly inactive, so good luck.

>I talk about Miyoo consoles or similars

Oh, i thought you were still talking about some halfly decent device like the rpi4.
There is no way some crap with 128MB ram and a very old arm cpu model would have decent performance with FBNeo, so i recommend not wasting more time on this. I'm still dumbfounded that after newer arm cpus got better, some people go back to something that is worse than the 1st raspberry pi model
