### ISSUE TITLE
Night slashers tempo to slow compare to real hardware

### ISSUE THREAD

**Issue by yoshi200215** [finalburnneo/FBNeo#1893]
Hello
The video game night slashers and clones has the tempo to slow and incorrect volume mixing compare to real hardware and ost
Emulator:
https://youtu.be/o6RQk8fFDYQ?si=_j8wbMXW_N6nbUyM
Real hardware:
https://youtu.be/AVI15b1lsOA?si=M4tVCdHCxKc3zZ0J
Ost:
https://downloads.khinsider.com/game-soundtracks/album/night-slashers-flower-busters

**Comment by barbudreadmon** [comment]
The framerate seemed incorrectly set, tempo should be fixed with https://github.com/finalburnneo/FBNeo/commit/25599b15db71266ed72e89fb48daeaad7bc2d4aa

I can't hear the "incorrect volume mixing", maybe @dinkc64 will want to check, otherwise i'll close soon.

note: i'm sick of repeating the same thing to you again and again, don't talk about ost ever again.

**Comment by yoshi200215** [comment]
But I play the game in the correct refresh rate

**Comment by barbudreadmon** [comment]
>But I play the game in the correct refresh rate

I'm not gonna waste my time trying to figure out what you mean by that. 
Update your core to the latest version, enable vrr_runloop, and it will work, not my problem if you fail to do so.

**Comment by yoshi200215** [comment]
I play the game in the latest version of fbn and the music tempo is still too slow compare to the ost

**Comment by barbudreadmon** [comment]
>ost

I'm not gonna waste any additionnal second on your idiocy.
