### ISSUE TITLE
Rampage World Tour (rmpwtr) Player 2 commands not working!

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#252]
In Rampage World Tour you can play only with player 1 (George) and player 3 (Ralph). Lizzy commands  aren't working, you can only start game for Player 2.

Thanks.

**Comment by dinkc64** [comment]
Ugg, unfortunately this bug is another one that has something to do with the buggy tms34010 cpu implementation we have.   Sorry about that, please use the player3 inputs for 2 player games.
Someday we will have a better cpu, but unfortunately the work required to port it is insidious and not something I look forward to doing for just a few games that I don't even like :(  (we're talking probably a week worth of work).  I will make a driver note for this one.

**Comment by fastpop72** [comment]
Ok thanks. Closing...
