### ISSUE TITLE
Ultimate Mortal Kombat 3 (umk3) inverted low/high commands?

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#297]
In UMK3 there are High Punch/Kick commands mapped to first buttons, afaik must be the Low Punch/Kick commands at first, like the others MK games.

**Comment by barbudreadmon** [comment]
I think button order in FBNeo follows original hardware's "wiring", not layout. In this case i would be in favor of following the layout, especially if it's currently different from mk1/mk2.

**Comment by fastpop72** [comment]
@barbudreadmon If you enter the service mode you can spot that the "low" commands are the first ones at the bottom like others mk games. And only with the "low" commands you can enter the "3-digits MK code" just before the match begins. For these reasons i think they are inverted. I can't say anything about the wiring ... i will search for the original wiring scheme.

**Comment by grant2258** [comment]
here is the physical layout and this one is 6 buttons https://rentmyarcade.net/sites/default/files/styles/panopoly_image_original/public/mk3_controlpanel.jpg?itok=BxiLyreA

**Comment by fastpop72** [comment]
The arcade button layout IS THE SAME from MK1 to UMK3. It's the layout pointed by @grant2258 

What i wonder is:

"In MK1, MK2 and MK3 there's this default button layout:

Button1: Low Punch
Button2: Low Kick
Button3: High Punch
Button4: High Kick
Button5: Block
Button6: Block2 / Run

Why UMK3 have this default button layout instead?

Button1: High Punch
Button2: Block
Button3: High Kick
Button4: Low Punch
Button5: Run
Button6: Low Kick

**Comment by grant2258** [comment]
@fastpop72 let me try explain whats going on here it could be a few things jamma is a standard for arcades. Some arcades require a kick harness this is where the controls plug in aka sf2. 

This plug is wired a specific was pin say pin 1 is low kick and pin2 is high kick. It could be the MK1 and UMK3 have different pin outs or the inputs are wrong in the driver. You would need to look up if mk1 has the same kick harness as umk3. 

Its important in mame (not sure how fbneo handles this) to keep the jamma standard so you know where button1 is pointing too so you can wire your panel correctly to button1 if your layout is different you always know where button1 is on the controller by the way you mapped it.

**Comment by barbudreadmon** [comment]
> Why UMK3 have this default button layout instead?

It appears i "fixed" default mapping for mk1/2/3 in the libretro port some time ago (https://github.com/libretro/FBNeo/commit/043b55ce09722633d3b2280bbd8ce3669e9fc7c5), and umk3 wasn't caught by my "fix" because it's unexpectedly not a clone of mk3. umk3 should be ok with https://github.com/libretro/FBNeo/commit/f373e02ee44417107f4741e6923170ddd4d21cbb

> Its important in mame (not sure how fbneo handles this)

Afaik, the order is not important in FBNeo, but i won't mess with driver's internal mapping here, because i'm not sure standalone orders mk inputs the same way than libretro (prior to my "fix")

**Comment by grant2258** [comment]
@barbudreadmon  I think in stand alone its not so important to automap everything if its wrong the user can just go in and define new buttons in the inputs you cant please everyone with default mappings as people use all different shap and sizes of controllers a gamepad doesnt always map well to an arcade panel. 

For example double dragon, double dragon2, pow  suits 3 buttons in a row in a arcade panel  its not so great playing it like that on an arcade panel with
```
 3 4
 1 2
```
Since your mapping to a retropad in libretro and aiming for gamepads only which to be fair is most common use. It suits your port for that mapping. Since all controllers on windows and linux can have different mapping on the buttons or even arcade panels you cant rely on mapping to a retropad shape.

**Comment by fastpop72** [comment]
@barbudreadmon Flawless Victory!

**Comment by grant2258** [comment]
its is good defaults for a gamepad only set up like libretro @fastpop72 if thats what your looking for i thought you where using standalone as you posted here.

**Comment by barbudreadmon** [comment]
> aiming for gamepads only

Are we gonna have this convo again ? In the first place doing what you want (reproducing arcade layout) is impossible in most cases, your mk arcade layout is a good example but (as i already said to you in the past) even most 3 buttons cabinets didn't have their buttons aligned.
So finding a good enough zeroconf mapping for everyone (including arcade sticks/panels properly mapped with retropad recommendations) made a lot more sense to me when programming the libretro port input layer.
```
3 (4)
1  2
```
is a perfectly fine choice for playing 3-4 buttons arcade games on arcade sticks/panels, it's not "gamepad-centric" at all, actually a lot of 4 buttons cabinets used "squared" layouts, it's just an arbitrary choice by the manufacturer. Furthermore, if some people aren't fine with those zeroconf mappings, they can still remap in any way they want through `Quick Menu > Controls`.

**Comment by grant2258** [comment]
yea 4 button games can be like that never seen 3 like that anyway its a libretro port not going to bother wasting time on how playing pow and ddragon 2 on a panel is less than convenient for me without remapping but its not a big deal at the end of the day. The sdl will have some command line options to map to gamepad or use barcade layout in time hopefully in the long run so things map more naturally for barcades ect thats the aim anyway.

**Comment by barbudreadmon** [comment]
> never seen 3 like that

You were talking about double dragon, the actual cabinets look like this : 

![dd1](https://i.pinimg.com/originals/d3/60/92/d36092d62d39cc364027849bbad80662.jpg)

![dd2](https://i.pinimg.com/originals/50/7d/9a/507d9aec178c7e6fb9b787ce767ef35f.jpg)

![dd3](https://i.pinimg.com/236x/eb/a9/97/eba9972a73b9ee0217fd41d1ad70fd66--s-dragon.jpg)

The fact is : it's impossible to reproduce without custom-made panels. I know some people will prefer a "lined" layout for those games, but it's not a sane default for a libretro core since it'll be ok only for arcade stick/panels, unlike the current layout which is ok for any controller.

**Comment by grant2258** [comment]
If you read my posts you would see i said its your mapping is a good for the retropad not so great for panels all the time. nothing wrong with that at all. What i will say is most games will map nice to classic gamepad mapping and 6 button panels without intervention and work on both anyway

**Comment by barbudreadmon** [comment]
> not so great for panels

Just a question of personal preference as i said, iirc you are the only guy who ever complained to me about lr-fbneo's 3 buttons layout.

**Comment by grant2258** [comment]
not many people use barcades then i guess and its its a retropad platform. Originally i thought the issue was port wide since it was posted here. Since its specifically libretro it not a big deal. Standlone works more the way i need it too for global mapping will stick that and work on the sdl port for my own needs.
