### ISSUE TITLE
Could you explain how to extract all Dats without launching the emulator, please

### ISSUE THREAD

**Issue by newton9278** [finalburnneo/FBNeo#332]
Hello,
it is to create a batch for rom managers : RomVault, ClrMamePro, Romulus....
What MS-Dos command ?
Thanks for your help
Best Regards,
Newton

**Comment by dinkc64** [comment]
it will have to be done for each system, since it's going to be in a batch file, that will not be a problem.

fbn -listinfo > arcade.dat
fbn -listinfomdonly > megadrive.dat
fbn -listinfopceonly > pce.dat
fbn -listinfotg16only > tg16.dat
fbn -listinfosgxonly > sgx.dat
fbn -listinfosg1000only > sg1000.dat
fbn -listinfocolecoonly > coleco.dat
fbn -listinfosmsonly > sms.dat
fbn -listinfoggonly > gamegear.dat
fbn -listinfomsxonly > msx.dat
fbn -listinfospectrumonly > speccy.dat
fbn -listinfonesonly > nes.dat
fbn -listinfofdsonly > fds.dat

that's all

**Comment by newton9278** [comment]
Thanks a lot Dink ! 💯 
Best Regards
