### ISSUE TITLE
[SGX] Madou Ou Granzort (japan) main sprite is 2 lines above

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#348]
![sgx_granzort-05-02-154809](https://user-images.githubusercontent.com/32760152/80868819-1b0fdd00-8c9d-11ea-97ea-c1bcbcd72e0a.png)

**Comment by dinkc64** [comment]
Hi fastpop72,
Some bad news about the pce/tg/sgx emulation:
I can only suggest right now to use something else for pce/tg/sgx emulation,  In order to fix the bugs you've mentioned - it will need a complete rewrite.  I hope to do this someday but every time I try, it seems like I can't find enough good information on pce emulation for the vdp.  Though for some good news, Ghouls n Ghosts on sgx is flawless  (or close to it)
best regards.
- dink

**Comment by fastpop72** [comment]
Thank you for clarify this! I won't test pce roms anymore for now....
