### ISSUE TITLE
MSX might be missing some keys

### ISSUE THREAD

**Issue by barbudreadmon** [finalburnneo/FBNeo#37]
Following a post at https://forums.libretro.com/t/fb-neo-and-msx-games/22610 , i tested `antarct` and i couldn't get past the title screen when it asks to press 1 (joystick) or 2 (keyboard). All buttons from the InputList seemed mapped so i think we lack some keys.

**Comment by dinkc64** [comment]
oh, yea - that's because I did a raw keyboard callback in the msx driver to give near-full access to the keyboard (along with the ability to record it)
For the callback thing, check burner/win32/run.cpp for cburnerKeyCallback.  
If you can't figure that out, there is another option, but it would require a re-write on my end.  not looking forward to that :)  but, if it must be done, let me know.

**Comment by barbudreadmon** [comment]
Ok thanks, no need for a re-write then, i'll try to port the callback :)
