### ISSUE TITLE
Metal Slug 5 (mslug5) in FB Neo's core for RetroArch on the Nintendo Switch

### ISSUE THREAD

**Issue by miguelkgt** [finalburnneo/FBNeo#371]
I have an issue where the only way I have found to play properly the console or AES version of the game Metal Slug 5 of the Neo Geo in FinalBurn Neo is by selecting "AES Japan" in Options ->BIOS 
and in Neo-Geo mode "Uee bios specified in BIOS dipswitch below".

Which means that when I choose Unibios 4.0 I can´t play properly in Region: USA, Mode: Console because as soon as I start "Mission 1" I am unable to use buttons, I can´t jump, shoot or throw grenades, basically buttons B, A and C. I can just move my character: go right or go left.

I remember years ago I had MAME (I don´t remember which version) in my PC and when I tried to play Metal Slug 5 in console mode this same problem appeared.
I was surprised when this year I found that in MAME 0220 this problem is somehow fixed and I am even able to use the new Unibios 4.0 and it doesn´t matter which region I choose, USA, EUR or JAP, the game works fine.

I would like to know why the difference and how I can fix this problem. Does MAME 0220 does something special to fix this problem I have? Is MAME and FB Neo so different? Does it has to do with specific files on the rom zip? What exactly happens?

Basically:

**Metal Slug 5 FB Neo romset with neogeo bios FB Neo romset**

On RetroArch (1.8.8) FB Neo core (v0.2.97.44 1573fcd) on the Nintendo Switch: 
The only way I found to play in console (AES) mode is by selecting "AES Japan" on Options -> BIOS. By doing this I can´t use Unibios 4.0, can´t access its cheats and I can´t access the soft dip to change Time, Credit, Blood, etc. (holding Start doesn´t work). If I select Unibios 4.0 in Options -> BIOS the game only lets me move my charachter.

--------------------------------------------------------------------------------------------------
**Metal Slug 5 MAME 0220 romset with neogeo bios MAME 0220 romset**

On mame220b on my PC: Can play correctly in console (AES) mode, doesn´t matter which region I choose. I am able to use Unibios 4.0 and its cheats. I can edit soft dip (Credits, Time, Blood, etc.)

**Comment by dinkc64** [comment]
This is a known problem with unibios and the fix is listed in their help/manual.
The fix is to go into the options menu of the game and set your buttons in the joy config, they all default to A if i remember correctly.

http://unibios.free.fr/knownissues.html

"Later games in the Metal Slug and Samurai Shodown series (MS X,3,4,5 and SS 4,5,5Sp) may not work correctly in console mode until after you have set up the game settings and controller config in the options menu (after starting a game). This problem is due to the games not setting up the initial backup ram data correctly for console mode if the game is first run on the system while it is in ARCADE mode **(you** must experience a 'GAME OVER' before the new settings are permanently saved)."****

**Comment by miguelkgt** [comment]
Thanks a lot.
