### ISSUE TITLE
Problem streaming with OBS 

### ISSUE THREAD

**Issue by Anths2016** [finalburnneo/FBNeo#412]
If I stream the screen of FBN-Fightcade 2 on Twitch, the screen appears litte, but with big black frame to the right...

See image:
https://ibb.co/X3vqkwg
(I change the colour from black to orange to highlight it better)

**Comment by barbudreadmon** [comment]
let's wait for another dev's thoughts, but it doesn't sound like a fbneo issue tbh

**Comment by dinkc64** [comment]
This is very strange, does it happen with regular fbneo (not fightcade)?

**Comment by Anths2016** [comment]
It is as if there was a black layer, above which there is the image of the game, which if reduced in size it leaves under black.
Sorry for bad english.

**Comment by barbudreadmon** [comment]
try Ctrl+S in OBS, i think it's required for stretching content

**Comment by Anths2016** [comment]
Don't works.

**Comment by barbudreadmon** [comment]
Ok, then maybe use crop top/left/right/bottom on the source ? It looks like this on OBS linux : 
![obs](https://user-images.githubusercontent.com/10391265/89163289-a25b3e00-d575-11ea-8d43-1f797e71d118.png)

Values would probably be very different for your case.

Anyway, i don't see this as a fbneo issue

**Comment by JordiRos** [comment]
I think this is due to how DirectX9 renderer is created in windowed mode (Dx9 Alternate). FBNeo creates a big d3dDevice as big as fullscreen resolution, but only "fills" an area equivalent to the window. So anything trying to capture the window via the d3ddevice will capture the whole black area too (like when using kkapture). If you are capturing Game, try capturing Window instead, it's an option in the OBS setup source capture.
I don't remember if the experimental does the same, might be worth trying. Otherwise other blitters might be safer to use, or use the cropping feature.

NB: I think this code was done intentionally to avoid recreating the device every time the window size changes? (especially when dragging)
I had some code to fix that, but recreating the device is more prone to desyncs and never got to enable it

**Comment by Anths2016** [comment]
Exact! I hope you will change the rendering mode, perhaps activating also the integer scaling.
