### ISSUE TITLE
Interest thread: Sega System C/C2

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#53]
Same CPU, sound, graphics as Genesis/Mega Drive, but with an additional Altera EPM5032 and Sega 315-5242 color encoder. Supports games like Puzzle & Action Ichidant/Tant-R, Columns, and Puyo Puyo.

**Comment by dinkc64** [comment]
sorry, we don't do requests for new drivers

**Comment by Panderner** [comment]
Sega Genesis Games supported on FB Neo but it's upgraded hardware, 68000 increase to 8.948862 MHz and ym3438 instead of ym2612 but it's mono audio. Why you don't do requests for new drivers?

**Comment by barbudreadmon** [comment]
> Why you don't do requests for new drivers?

Should be obvious : because none of us has unlimited time, and it is a hobby, so we want to work on things which interest **us**.

**Comment by dinkc64** [comment]
Panderner, to put things into perspective:
a new driver takes a week at 4-6hrs/day to complete, even if we have parts from another driver.
Or, even better example: NES emulation.  I spent 6h/day since september '19 to mid-january 19!  It's not completely finished yet :/

Don't answer this question, but think about it:  will you give me a week of your time @ 6hrs/day?

The answer is: if we love the idea and the system, it will make it in some day.

Right now the best thing anyone can do to help FB project:
1: report bugs, this makes it better for everyone :)
2: write code for the project

best regards,
- dink

**Comment by Panderner** [comment]
> Panderner, to put things into perspective:
> a new driver takes a week at 4-6hrs/day to complete, even if we have parts from another driver.
> Or, even better example: NES emulation. I spent 6h/day since september '19 to mid-january 19! It's not completely finished yet :/
> 
> Don't answer this question, but think about it: will you give me a week of your time @ 6hrs/day?
> 
> The answer is: if we love the idea and the system, it will make it in some day.
> 
> Right now the best thing anyone can do to help FB project:
> 1: report bugs, this makes it better for everyone :)
> 2: write code for the project
> 
> best regards,
> 
> * dink

And how about new Arcade Drivers with 68000 CPU and why you don't have plans for add 3d based games?

**Comment by barbudreadmon** [comment]
> And how about new Arcade Drivers with 68000 CPU and why you don't have plans for add 3d based games?

The answer is still the same

**Comment by dinkc64** [comment]
We are working on new drivers all the time, it just takes time to get them ready to release.
