### ISSUE TITLE
4 players not detected on certain games (retroarch-win10)

### ISSUE THREAD

**Issue by toccata10** [finalburnneo/FBNeo#756]
I have some trouble with multiplayer on fbneo, on windows 10: some games refuse to see more than 2 players (that's mysticwarr, nbajamte) while others (simpsons, ssriders) work fine with 4 players.
The problematic games work correctly with 4 players on linux and on the standalone version of fbneo on windows.
I join a few screenshots: first is my general input config in retroarch for controller 3.
![01](https://user-images.githubusercontent.com/7478580/114817470-57f3b780-9dba-11eb-9662-a17c7d5f562e.PNG)
Second is what I have on nbajamte (with the dipswitch set to 4).
![02](https://user-images.githubusercontent.com/7478580/114817480-5d510200-9dba-11eb-9fac-c127faa70e4e.PNG)

Third, is what I have in the quickmenu>controls: nothing for player 3 (I can't select anything).
![03](https://user-images.githubusercontent.com/7478580/114817490-617d1f80-9dba-11eb-92c0-3417493bdb51.PNG)

Fourth is what I have on the same screen but with the simpsons.
![04](https://user-images.githubusercontent.com/7478580/114817509-680b9700-9dba-11eb-81a7-b8114faeb96d.PNG)

I tried with some controllers connected directly and made another attempt with controllers connected through a steamlink. Exactly the same result.
I reported this problem on retroarch's discord, but it got quickly burried, so I'm trying here (although it seems more a retroarch than a fbneo problem).
And, of course: thanks for this fantastic emulator !

**Comment by barbudreadmon** [comment]
> The problematic games work correctly with 4 players on linux

Hmm, that's a bit weird, there shouldn't be any difference between linux and windows as far as the libretro port is concerned, especially if the issue is what i fixed. Maybe you were talking about the linux sdl port ?

> I reported this problem on retroarch's discord

I don't recommend doing that, or please tag me (barbudreadmon) when you do, there is no way i would notice someone is asking help about FBNeo on that huge discord server if i'm not tagged. The alternative would be to join us on our discord at https://discord.gg/8EGVd9v

**Comment by toccata10** [comment]
Closing this as it is now resolved: I've just tested the problematic games on windows: they all play fine with 4 players.
Only a few hours after the bug was opened, it's already resolved: awesome!
