### ISSUE TITLE
Rygar arcade: Voices too high and weird sound after death. 

### ISSUE THREAD

**Issue by TesterNes** [finalburnneo/FBNeo#777]
Hi Guys!
I've found rygar arcade has the player voices too high and a strange sound happen after death. 
I hope you can check this. 
I've prepared a video for you to compare. 
https://www.youtube.com/watch?v=OAR6X7ziJmo

Thank you.

**Comment by dinkc64** [comment]
Hi, please give it a try now,
The dac volume still might be too high, its hard for me to tell today.

best regards,
- dink

**Comment by dinkc64** [comment]
oops, I didn't mean to close this. :)

**Comment by TesterNes** [comment]
Thanks for looking into this. 
Yes, it's still a bit high yet, and the noise after death it's much better now, but it has a little crackle just before the letters "Player 1 Let's Fight" disappear. 

Thank you for doing this dink.

**Comment by dinkc64** [comment]
I did a little more tweaking, please give it a try now :)
the "crackles" in the version from before the previous fix were caused by a bug in the stream updater code of the msm5205 adpcm/dac.  In this new update, I tried to better match the volume as well as put a dc blocker on the msm5205 chip, as there was quite a nasty dc offset halfway through the death sample - which lead to a louder click at the end.  Most amps have a .1uf cap on the input which does the same thing as the dc blocker code I used.

There still remains a little noise at the end of the death sample - which is now quite hard to notice, but if you really pay close attention, it's in the pcb recording as well - it's right before the jump sample.

Renegade has the exact same noise when you coin up w/the "good luck kid" sample.  I believe it's the noise of someone setting down a microphone -or- pressing stop on the tape recorder after recording their voice :)  I guess they didn't have good sample editors back then - who knows :)

best regards,
- dink

**Comment by TesterNes** [comment]
That's an interesting hypothesis. When you spend your lives and the death is taking you away, I can hear the noise you're talking about.
Despite that, I'm still hearing the voices a little bit high... a good measurement could be that the landing sound after jumping, it has to be louder than the voices are, as well as the sound of breaking the tombs from the floor to get the items. 
https://www.youtube.com/watch?v=xlr3W77-1CI

I don't want to monopolize your time with this... With your work it's much better now than it was so thank you endlessly and close the issue when you consider it.

**Comment by dinkc64** [comment]
Thanks for the input :)
After watching the video a bit: I think the volume is right, but there is a filter (most likely lowpass) that is attenuating the high freqs.   Will post back here after doing some experimenting.

**Comment by dinkc64** [comment]
After tossing on a 2khz lpf, it sounds a lot closer.  It's not 1:1 with the video, but about as good as I can get it for now :)

best regards,
- dink

**Comment by TesterNes** [comment]
Thank you Dink!
