### ISSUE TITLE
namco_snd.cpp is trashing memory (soundbuf too small)

### ISSUE THREAD

**Issue by wskan** [finalburnneo/FBNeo#830]
soundbuf is not big enough.  it should be

	//soundbuf = (INT16*)BurnMalloc(0x1000); // for buffered updates
	soundbuf = (INT16*)BurnMalloc(0x1000 + 5 * sizeof(INT16)); // for buffered updates

**Comment by barbudreadmon** [comment]
Could you give more details about the game you used for your tests ? I run the address sanitizer on our full library from time to time so i'm kinda surprised such an issue went past it.

**Comment by wskan** [comment]
I believe it was youkaidk1 or youkaidk2.

**Comment by barbudreadmon** [comment]
Hmmm, i'll need more details on how to reproduce those out-of-bound issues, they don't seem to happen for me.

**Comment by wskan** [comment]
in UpdateStream(), there are these code

```
	INT16 *mix = soundbuf + 5 + (nPosition * 2); // * 2 (stereo stream)
	if (chip->stereo)
		NamcoSoundUpdateStereo_INT(mix, nSamplesNeeded);
	else
		NamcoSoundUpdate_INT(mix, nSamplesNeeded);
```
but inside either of those update function, it called
```
memset(buffer, 0, length * 2 * sizeof(INT16));
```
which effectively 0 out the extra 5*sizeof(INT16) bytes.

it could be a local change when my nBurnSoundLen happened to be 1024, and soundbuf was hardcoded with size of 0x1000.

**Comment by barbudreadmon** [comment]
>nBurnSoundLen happened to be 1024

Are you developping your own port or something ? That `nBurnSoundLen` value is wrong, the formula for sound length is the following : 
```
(sample_rate * 100 + (fps >> 1)) / fps
```
Authorized values for sample_rate are 44100 or 48000, and fps is actually the framerate * 100 (meaning the value would be 6000 for youkaidk1/youkaidk2). So `nBurnSoundLen` will be either 735 or 800 depending on your samplerate here.

Anyway, i'll let @dinkc64 look at this since he is a far better sound core specialist than me. But that memory trashing don't seem to ever happen (assuming you are in a normal scenario where your sound length was calculated properly)

**Comment by dinkc64** [comment]
(decimal) 800*2*2 (48k) is 0xc80, and the buffer is 0x1000 (4096 dec.)
I don't understand how this is overflowing, unless you're trying to run at 96khz ?

**Comment by dinkc64** [comment]
@wskan is this still a problem? :)
