### ISSUE TITLE
Gekirindan, another RA 2nd instance glitch

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#836]
Another small one but it could be interesting to fix:
Gekirindan (Ver 2.3J) isn't showing the red-pink bonus text at the end of a level when using run ahead 2nd instance in retroarch.

It's working fine with only 1 instance:
![gekiridnj-210814-234543](https://user-images.githubusercontent.com/6266038/129461053-ac05924b-0ed4-4202-9516-e61d39762c5c.png)

Switching to 2nd instance on that screen can cause another glitch like that:
![gekiridnj-210814-234658](https://user-images.githubusercontent.com/6266038/129461067-8d8d5aaa-eac2-4c57-94ac-586141747d74.png)

**Comment by dinkc64** [comment]
hmm, this one is tough, might have to get barbudreadmon to help me w/some tests here.  It looks like the game is losing the lineram state.  will give it some more time later today :)

**Comment by dinkc64** [comment]
@barbudreadmon, if/when you get a chance, try this in d_taitof3.cpp
if (nAction & ACB_WRITE && ~nAction & ACB_RUNAHEAD) {
to 
if (nAction & ACB_WRITE) {

single instance runahead (in fbneo.exe) needs that in order to not chew cpu every frame, so, if that fixes it, we'll have to brainstorm another way of doing things.

**Comment by barbudreadmon** [comment]
@dinkc64 i gave it a try, it seems to solve the issue indeed

**Comment by barbudreadmon** [comment]
Closing as all mode-related runahead instance issues have supposedly been fixed.
