### ISSUE TITLE
XML cheat support

### ISSUE THREAD

**Issue by 16mpx** [finalburnneo/FBNeo#855]
Any possibility to add XML cheat support ? Thanks.

**Comment by IAMNOTRANA** [comment]
I really want .xml option too instead of relying on .dat or .ini. I dunno about .dat format documentation but .ini is very limited and some cheats can't be converted from .xml format like metal slug 3-5 autofire cheat.

**Comment by dinkc64** [comment]
No, the code required to do the xml stuff would probably outweigh FBNeo itself, so that doesn't make sense.
-but-
xml cheats can easily be converted to .dat if you know what you're doing.  At least, I can do them easily.  request them on the forum if interested.

Cheat Requests
https://neo-source.com/index.php?topic=139.60

**Comment by dinkc64** [comment]
sorry, hit the wrong button.

**Comment by 16mpx** [comment]
Thank you

**Comment by 16mpx** [comment]
Thank you for your comments,

I am closing the issue for now.

**Comment by barbudreadmon** [comment]
>I am closing the issue for now.

Feel free to let us know if you encounter other cheats that don't seem translatable to dat/ini :)
