### ISSUE TITLE
Build Error (Linux)

### ISSUE THREAD

**Issue by sdgoodrick** [finalburnneo/FBNeo#861]
I get a build error on Arch Linux. I have installed all the dependencies from the README, including both the 64-bit and 32-bit versions of SDL2 and SDL2_image.

```
$ make sdl2
Making debug build...

Generating depend file for d_badlands.cpp...
In file included from d_badlands.cpp:5:
m68000_intf.h:17:11: fatal error: m68k/m68k.h: No such file or directory
   17 |  #include "m68k/m68k.h"
      |           ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [makefile.sdl2:582: d_badlands.d] Error 1
make: *** [makefile:97: sdl2] Error 2
```

**Comment by barbudreadmon** [comment]
I doubt an interrupt could be the problem, firstly because i can't reproduce it no matter how many times i interrupt the build, secondly because i don't see how it could delete this header (unlike a few others, it's not a generated header, so the file is always there) or forget about the included paths.

That error just seems plain impossible to me if a copy of our current repo was made, no change was done to its content, and `make sdl2` was run from its root directory.
