### ISSUE TITLE
tmnt2, ssriders and clones

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#878]
- In TMNT2 stage 4 "Prehistoric Turtlesauras" when it enters the cave, some rays of light illuminate the characters in the original pcb and not in the emulator.

- In ssriders at the dance demo scene with spot lights, some lighting effects are not applied properly.

- In suratk, sprites behind the glass wall in level 3 (also seen in attract mode) should be dark

![TMNT2](https://user-images.githubusercontent.com/22105571/143685868-2e7f2ca5-e5e4-4415-9f24-bc9c032344a0.jpg)

![ssriders](https://user-images.githubusercontent.com/22105571/143685883-43228bec-7894-4cb2-b91c-ccbaba362407.jpg)

![suratk](https://user-images.githubusercontent.com/22105571/143685960-bb05dba0-4158-4b0b-b52a-ca47da4d2ad6.png)

**Comment by dinkc64** [comment]
Hi,
I appreciate that you want to try to help.  Please remember these when reporting a bug:

1) If the bug is on mametesters first check to see if it also applies to fbneo.  
2) If the bug is on mametesters, we already know about it - especially bugs that have existed for a decade or more.
3) if the bug is on mametesters and exists in fbneo and mame - there's a high chance that more than 1 person has spend countless hours over the years trying, trying again, and keep on trying again and again and again to try to fix the problems, but it's just not possible at this time.
4) it's only necessary to post the bug once (here or on the forum)

Here's the response to this report, from the forum:
https://neo-source.com/index.php?topic=3647.msg33184#msg33184

best regards,
- dink
