### ISSUE TITLE
G.I. Joe info with 2 players max instead of 4 players max

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo#889]
I noticed that there is only 2 players max for info instead of 4 players max for G.I. Joe and clones info for Final Burn Neo Emulator.

**Comment by barbudreadmon** [comment]
You already reported this and it was fixed for parents and several of its clones yesterday. Are you using our wip builds from https://github.com/finalburnneo/FBNeo-WIP-Storage-Facility/releases/tag/appveyor-build as i asked you several times already ?

Anyway, the 4p info was overlooked for some of the clones, so that's a good thing i took another look, thanks for the report

**Comment by jmodlin210** [comment]
yes I am using the wip builds for final burn neo emulator.

**Comment by barbudreadmon** [comment]
>yes I am using the wip builds for final burn neo emulator.

Than why are you reporting that the gijoe parent has a 2p max info while it was corrected yesterday ?
