### ISSUE TITLE
Light Bringer, run ahead glitch

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#959]
This one is about the little glitches that appear in libretro when using run ahead with 2 instances.
In Light Bringer the lifebars and texts are disappearing while it doesn't happen with run ahead 1 instance.

**Comment by dinkc64** [comment]
Hi Tatsuya79,
Does it happen if you start it in 2 instance mode?

**Comment by barbudreadmon** [comment]
@dinkc64 this one indeed only happens if you switch from 1-instance to 2-instances at runtime, everything is fine if you start the game with 2-instances

**Comment by barbudreadmon** [comment]
This is about https://github.com/finalburnneo/FBNeo/blob/70d7a50ad0998bb44b86b1410536ac94da6cf1b0/src/burn/drv/taito/d_taitof3.cpp#L1651-L1661

libretro doesn't give a context when asking a savestate... so i'm never setting `ACB_RUNAHEAD` because i never know if runahead is enabled or not...

I suppose we could do this : 
```
#ifndef __LIBRETRO__
		if (nAction & ACB_WRITE && ~nAction & ACB_RUNAHEAD) {
#else
		if (nAction & ACB_WRITE) {
#endif
```

**Comment by dinkc64** [comment]
The && ~nAction & ACB_RUNAHEAD is making sure it's not in (main) fbneo's runahead mode, so it doesn't have to decode vram characters etc every single frame while in runahead.

if you're not setting nAction |= ACB_RUNAHEAD then it will still be true when loading a state (notice the ~ ?). 
~nAction & ACB_RUNAHEAD is the same as "(nAction & ACB_RUNAHEAD) == 0"

best regards,
- dink

**Comment by dinkc64** [comment]
barbudreadmon:
to clarify: in the state ACB_WRITE, I'm checking if its in run-ahead and not re-decoding things as a speed-up only, so not having ACB_RUNAHEAD in nAction won't make a difference either way on libretro.

Tatsuya79:
With the complexity of some systems (Taito F3 for example), it's impossible to support changing the run-ahead mode in-game without glitches,  which is why I asked.  It should be fine if you set the desired mode, then restart the game, right?  If that's not the case, do let me know and I'll try to dig deeper with this issue.

best regards,
- dink

**Comment by barbudreadmon** [comment]
shit, i think something changed in retroarch, and because of that change my code is now applying the net optimization flag `ACB_NET_OPT` on all frames for runahead, which turns out having the same value as `ACB_RUNAHEAD`, i'll change it

**Comment by dinkc64** [comment]
ACB_RUNAHEAD is strictly for single-instance runahead, just letting you know in-case someday libretro adds a feature for getting runahead status in the future.

**Comment by barbudreadmon** [comment]
I asked for context-awareness in savestates a long time ago, i'm still hoping they'll implement it someday...

**Comment by Tatsuya79** [comment]
I tried again with the latest libretro core and it's working fine.
Thank you. :)
